default: &default
  adapter: postgresql
  encoding: unicode
  database: node_rails_presentation
  pool: 3
  username: node_rails_presentation

development:
  <<: *default
  database: node_rails_presentation_development

test:
  <<: *default
  database: node_rails_presentation_test
